spring:
 profiles:
  active:
   - dev
---
server:
 pory: 8201
spring:
 profiles: dev
  application:
   name: microservicecloud-config-client
eureka:
 client:
  service-url:
   defaultZone: http://eureka-dev.com:7001/eureka/
---
server:
 pory: 8202
spring:
 profiles: test
  application:
   name: microservicecloud-config-client
eureka:
 client:
  service-url:
   defaultZone: http://eureka-test.com:7001/eureka/